alter table users
  drop column if exists weight_class,
  drop column if exists first_name,
  drop column if exists last_name,
  drop column if exists nickname,
  drop column if exists phone_number,
  drop column if exists date_of_birth,
  drop column if exists gender,
  drop column if exists current_weight_class,
  drop column if exists height,
  drop column if exists reach,
  drop column if exists country,
  drop column if exists city,
  drop column if exists status,
  drop column if exists profile_picture,
  drop column if exists bio,
  drop column if exists profile_created_at,
  drop column if exists profile_updated_at,
  drop column if exists total_fights,
  drop column if exists wins,
  drop column if exists losses,
  drop column if exists draws,
  drop column if exists awards,
  drop column if exists record_confirmed,
  drop column if exists record_confirmed_at,
  drop column if exists record_confirmed_by,
  drop column if exists record_admin_notes;

